# Generated by Django 3.0.3 on 2020-06-05 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20200605_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pid',
            field=models.IntegerField(default=0),
        ),
    ]
