# Generated by Django 3.0.3 on 2020-06-05 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_pid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='featured',
            field=models.BooleanField(default=True),
        ),
    ]
