# Generated by Django 3.0.3 on 2020-06-06 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20200606_1141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homeimages',
            name='discount',
        ),
        migrations.AlterField(
            model_name='homeimages',
            name='price',
            field=models.DecimalField(decimal_places=2, default=False, max_digits=10),
        ),
        migrations.CreateModel(
            name='DiscountField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('new_price', models.DecimalField(decimal_places=2, default=False, max_digits=10)),
                ('discountfield', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.HomeImages')),
            ],
        ),
    ]
