# Generated by Django 3.0.3 on 2020-06-06 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20200606_1203'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HomeImages',
            new_name='Places',
        ),
    ]
