# Generated by Django 3.0.3 on 2020-06-07 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_carousel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Carousel',
        ),
    ]
