# Generated by Django 3.0.3 on 2020-06-08 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_auto_20200607_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='body',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
