# Generated by Django 3.0.3 on 2020-06-08 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_auto_20200608_0956'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotepics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='quotes')),
                ('description', models.TextField(blank=True, null=True)),
                ('featured', models.BooleanField(default=False)),
            ],
        ),
    ]
