# Generated by Django 3.0.3 on 2020-06-18 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_auto_20200618_1322'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='blog',
            unique_together=set(),
        ),
    ]
