# Generated by Django 3.0.3 on 2020-06-18 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_auto_20200618_1413'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='blog',
            unique_together={('slug', 'title')},
        ),
    ]
