# Generated by Django 3.0.3 on 2020-06-18 15:11

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0027_auto_20200618_1959'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turorial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('published', models.DateTimeField(default=datetime.datetime(2020, 6, 18, 20, 41, 3, 698207))),
                ('tutorial_slug', models.CharField(default=1, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TurorialCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutorial_category', models.CharField(max_length=100)),
                ('category_summary', models.CharField(max_length=200)),
                ('category_slug', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TurorialSeries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutorial_series', models.CharField(max_length=200)),
                ('series_summary', models.CharField(max_length=100)),
                ('tutorial_category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='products.TurorialCategory')),
            ],
        ),
        migrations.DeleteModel(
            name='Upload',
        ),
        migrations.AddField(
            model_name='turorial',
            name='tutorial_series',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='products.TurorialSeries'),
        ),
    ]
