# Generated by Django 3.0.3 on 2020-06-19 02:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0028_auto_20200618_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turorial',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 19, 8, 16, 17, 120166)),
        ),
    ]
