# Generated by Django 3.0.3 on 2020-06-19 05:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0029_auto_20200619_0816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turorial',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 19, 10, 40, 14, 242549)),
        ),
    ]
